### PR TITLE
Fix mistakes at description of 'HTML blocks'

### PR DESCRIPTION
**Pull request by vanou**
- Fix mistakes
  Three inline link texts 'end condition' with no link destination

### CODE REVIEW

**Comment by jgm** [comment]
What's the mistake?  `[end condition](@)` defines an anchor and should occur only once.  The other links will work automatically.

Note: this is NOT a standalone commonmark file. It is in a special format which is designed to be processed using `tools/make_spec.lua`.

**Comment by vanou** [comment]
@jdm
> Note: this is NOT a standalone commonmark file. It is in a special format which is designed to be processed using `tools/make_spec.lua`.

Thanks. I understand.

I wanted to fix **link break** in this PR.
See [HTML blocks](https://spec.commonmark.org/0.29/#html-blocks), because `end condition` is referenced as https://spec.commonmark.org/0.29/#end , other shortcut reference links get break.

Any way this PR is wrong one. Thanks.

**Comment by jgm** [comment]
Yes, you're right -- that's a legitimate bug!  I just didn't see what it was from your PR.

**Comment by jgm** [comment]
I've fixed this in master by fixing the program that generates the HTML from spec.txt.

**Pull request closed without merging**
