### PR TITLE
Test new entity length constraints

### PR DESCRIPTION
**Pull request by MihaZupan**
This now tests that an entity with 8 arabic digits is no longer recognised

### CODE REVIEW

**Comment by mity** [comment]
Maybe the limit for the hexadecimal variant should then be tested too.

**Comment by MihaZupan** [comment]
The new limit for hexadecimals is tested by [example 314](https://spec.commonmark.org/0.29/#example-314)

**Comment by mity** [comment]
No, it is not.

`&#abcdef0;` does not contain the `x`.

**Comment by MihaZupan** [comment]
Ah, mb.

Looks like commonmark.js does not take the new length limit into account
[babelmark](https://babelmark.github.io/?text=Valid+%26%23xabcdef%3B%0A%0ANot+valid+%26%23xabcdef0%3B)

**Comment by jgm** [comment]
babelmark III is running an old version (0.28.1).
Try https://johnmacfarlane.net/babelmark2/?normalize=1&text=lid+%26%23xabcdef%3B%0A%0ANot+valid+%26%23xabcdef0%3B%0A

**Pull request merged**
