### PR TITLE
Improve `spec_tests.py` (refactor, catch invalid utf-8, add `--track`)

### PR DESCRIPTION
**Pull request by not-my-profile**
If you like these changes, please merge them without squashing.

### CODE REVIEW

**Comment by jgm** [comment]
Looks good to me, thanks.  (I know, I write python like a functional programmer and it isn't idiomatic.)

**Comment by jgm** [comment]
Ack, porting this over to cmark breaks a lot of things!
cmark includes additional tests that import some of these modules, and the changes in signatures are causing problems.
(Also, I note that cmark had a few minor changes to spec_test.py and cmark.py which should be integrated: more accurate types for the ffi + the addition of `--unsafe` to the executable, without which the tests fail.)
It would be nice to keep this in sync with what is actually used in the cmark library, if possible.  Either we could revert these changes, or cmark could be fixed up?

**Comment by not-my-profile** [comment]
Sorry about that, I didn't know that `cmark.py` was used elsewhere.

To be frank I think it would be best to remove all implementation-specifics from the test framework of a specification. CMark could include this repository as a Git submodule and `spec_tests.py` could be adapted to provide an API that would allow the ffi library specifics to be outsourced to the cmark repository. Do you agree?

**Comment by jgm** [comment]
I agree that ffi specifics (and even the assumption that `--unsafe` should be added) belong in cmark rather than here, so it could be nice to separate these things.
Less sure about using git submodules. I never liked working with them.  (Note that it would be important for cmark to tie down a particular commit of commonmark-spec as a submodule, but I assume that's possible with submodules?)

**Comment by not-my-profile** [comment]
Yeah, git submodules unfortunately can be a bit finicky but I think for this it makes sense. I am pretty sure that git actually requires submodules to point to a specific commit, so that's not a problem. I'll see what I can come up with.

**Comment by jgm** [comment]
Instead of using submodules, I might prefer a low-tech solution, where the files are duplicated in the cmark repository, but a Makefile target ensures that they're kept in sync.
I'd like it to be the case that you can just clone the repository and build, without having to use git submodule commands.

**Pull request merged**
